### ISSUE TITLE
Errors on lines 20 to 23 @ src/main/java/com/herb_mc/extra_enchants/enchantments/Barbaric.java

### ISSUE THREAD

**Issue by Unselfish** [herb-mc/extra_enchants#1]
Good morning.

I found an error on these lines.

https://github.com/herb-mc/extra_enchants/blob/0fb12130f978b0daae2a33e1e2b6e1b12d0b71e5/src/main/java/com/herb_mc/extra_enchants/enchantments/Barbaric.java#L20-L23

This code looks like Java which is now outdated. Why are you using Java? You can rewrite it in Rust for faster code.

Here's how it can look in Rust.

`1`

Rust is a multi-paradigm programming language designed for performance and safety, especially safe concurrency. Rust is syntactically similar to C++, but can guarantee memory safety by using a borrow checker to validate references. Rust achieves memory safety without garbage collection, and reference counting is optional.

Warm wishes,
Thanks,
thanks!

**Comment by Unselfish** [comment]
P.S. I will star4star

**Comment by herb-mc** [comment]
I will rewrite the entire spongepowered library in rust now thank you for the advice.
