### ISSUE TITLE
Multiple enchantements not available in the creative menu categories

### ISSUE THREAD

**Issue by ascent08** [herb-mc/extra_enchants#2]
I have been able to find all but 6of the enchantments this mod adds in the creative menu by looking through the Combat and Tools categories. I can find the remaining 6 by searching for them in the creative menu, and they are not listed under any categories. These enchantments are:
- Barbaric
- Bounding
- Cleaving
- Surface Skimmer
- Swiftness
- Warding

Examples of what I mean are shown below:
![surf skim](https://user-images.githubusercontent.com/59103728/125378931-d8d83600-e34c-11eb-9cb8-c2b5b4e29e2f.png)
![toug](https://user-images.githubusercontent.com/59103728/125378933-d970cc80-e34c-11eb-8c5d-dd3fbba2f7dd.png)

**Comment by herb-mc** [comment]
This is an issue with the registry. Should be resolved next release.

**Comment by herb-mc** [comment]
enchantments should now be visible in creative menu. horse armor enchants may be found in the miscellaneous category.
