### ISSUE TITLE
Minecraft crashing when I add this mod.

### ISSUE THREAD

**Issue by ULTIMATUM001** [herb-mc/extra_enchants#4]
Occurs when I add this mod with my other mods. I love this mod and I would love it if this was fixed, thank you. 

Crash report:

---- Minecraft Crash Report ----
// You're mean.

Time: 8/11/21, 12:02 AM
Description: Initializing game

java.lang.NoSuchFieldError: renderer
	at net.minecraft.class_757.<init>(class_757.java:278)
	at net.minecraft.class_310.<init>(class_310.java:565)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_128.handler$bgm000$fillPatchouliContext(class_128.java:521)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$bgm000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.client.main.Main.main(Main.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 6587877936 bytes (6282 MiB) / 7348420608 bytes (7008 MiB) up to 7348420608 bytes (7008 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20438.70
	Virtual memory used (MB): 12916.72
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 249.95
	JVM Flags: 10 total; -Xmn128M -Xmx7000M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 1.2.1
		aqupdgrizzly: Grizzly Bear mob 1.1.1
		architectury: Architectury 2.3.24
		autosmeltenchant: AutosmeltEnchant 1.1.0
		baritone: Baritone 1.7.0
		bclib: BCLib 0.2.4
		betterend: Better End 0.10.5-pre
		betterf3: BetterF3 1.1.5
		betternether: Better Nether 5.1.3
		betterthanmending: BetterThanMending 1.3.0
		blur: Blur (Fabric) 2.1.0
		bno: Basic Nether Ores 1.17-6.0.0-Fabric
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		craftable_enchanted_golden_apple: Craftable Enchanted Golden Apple 1.0.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portals 0.0.1-beta33-1.17
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		dawn: Dawn API 2.0.5
		dual_riders: DualRiders 1.0.5
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.1
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.2
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.2
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.1
		extra_enchants: Extra Enchants 0.1.2
		fabric: Fabric API 0.37.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fermion: Fermion 2.11.241
		fermion-modkeys: Fermion Modifier Keys 1.10.241
		fiber: fiber 0.23.0-2
		forgottenrecipes: Forgotten Recipes 1.0.2
		geckolib3: Geckolib 3.0.11
		gildedarmor: Gilded Armor 1.3.0+fabric-1.17.1
		grindenchantments: Grind Enchantments 1.2.1+1.17
		imm_ptl_core: Immersive Portals Core 0.20
		immersive_portals: Immersive Portals 0.20
		impaled: Impaled 1.0.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		lacrimis: Lacrimis 2.1.3+1.17.1
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.4+1.17.1
		libninepatch: LibNinePatch 1.1.0
		maybe-data: Maybe data 1.0.1-1.17
		meteor-client: Meteor Client 0.4.5
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.17.1
		modmenu: Mod Menu 2.0.4
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		noenchantcap: NoEnchantCap 4.1.0
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		outvoted: Outvoted 2.0.0-alpha.11
		patchouli: Patchouli 1.17-54-FABRIC
		piglib: Piglib 1.0.1
		promenade: Promenade 2.1.2
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.20
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 2.2.0+1.17.1
		satin: Satin 1.6.0-nightly.1.17-pre3
		seedy-behavior: Seedy Behavior 1.0.1
		silkspawners: SilkSpawners 1.0.2
		sit: Sit 1.17-12
		sodium: Sodium 0.3.0+build.5
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.3
		stuffz: StuffZ 2.3.2
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		the_aether: The Aether 1.17.1-1.5.0
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-11
		transportables: Transportables 1.0.5
		trinkets: Trinkets 3.0.2
		truerooms: True Secret Rooms 1.1.5
		tweed: Tweed API 3.0.0-beta.22
		veinmining: Vein Mining 0.0.10-1.17
		villagersleashed: Villagers Leashed! 1.0
		wandering_collector: Wandering Collector 1.0.2+mc1.17
		waystones: Waystones 2.0.3
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		wrenchable: Wrenchable 1.1.0+1.17
		xaerominimap: Xaero's Minimap 21.15.0.1
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GT 1030/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.41, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz

**Comment by herb-mc** [comment]
I suspect it has something to do one with of your mods. Unfortunately this is difficult to diagnose, but I have pushed a possible fix for this anyways. Please check the [current alpha build](https://github.com/herb-mc/extra_enchants/releases/tag/v0.1.3a) to see if your problem is fixed.
