### ISSUE TITLE
Crash on startup caused by conflicting enchants with another mod

### ISSUE THREAD

**Issue by 3th3** [herb-mc/extra_enchants#5]
I won't log the crash report. There is no need to, here is the important snippet.
@ModifyConstant conflict. Skipping extra_enchants.mixins.json:LivingEntityMixin->@ModifyConstant::applyReflex(I)I with priority 1000, already redirected by sihywtcamc.mixins.json:shield.LivingEntityBlockingMixin->@ModifyConstant::instantlyBlock(I)I with priority 1000

Seems simple enough, reflex is conflicting with instantblock. The conflicting mod is [https://www.curseforge.com/minecraft/mc-mods/sihywtcamc#c37](url). I don't think instantlyBlock is an enchant, however. Its supposed to be a new trait to shields in general.

**Comment by charlyb01** [comment]
The reflex enchantment modifies the same constant value as I do (in my mod) to block instantly. I guess we can solve this compatibility issue by setting different priority levels for our changes but I'm not sure about it as I never did this. I'll check that a bit later and tell you

**Comment by herb-mc** [comment]
I'll look into this on my end as well, I will see if I can do away with the ModifyConstant entirely as to avoid this issue in the future

**Comment by herb-mc** [comment]
I have addressed this particular compatibility issue in the [latest alpha release](https://github.com/herb-mc/extra_enchants/releases/tag/v0.1.3a-1). I will let this issue remain open until I publish an official release.

**Comment by charlyb01** [comment]
Good, I'll do the same change to my mod I guess so that mine won't have the issue with another mod doing the same. Thanks

**Comment by 3th3** [comment]
> I have addressed this particular compatibility issue in the [latest alpha release](https://github.com/herb-mc/extra_enchants/releases/tag/v0.1.3a-1). I will let this issue remain open until I publish an official release.

Thanks bunches! Happy to know I can use both of these mods at once again when the update releases

**Comment by charlyb01** [comment]
Fixed in the lastest version of my mod too. It works fine using both of these mods now.
Reference: [commit](https://github.com/sf-inc/sihywtcamc/commit/10fabd6279eaad036e9babaef2cd620aab32210e)
