### ISSUE TITLE
Windstep cant step up a block + 1 pixel

### ISSUE THREAD

**Issue by milkev** [herb-mc/extra_enchants#6]
when attempting to step up a block from say, farmland or a path, to a regular block, windstep doesnt autostep up it
(holding w in image)
![2021-08-16_09 58 52](https://user-images.githubusercontent.com/22010128/129593296-f1496ad3-73e4-43e8-bb3d-f8153a422ed8.png)

**Comment by herb-mc** [comment]
This is part of how Windstep is designed. Add [this datapack](https://github.com/herb-mc/extra_enchants/files/6997691/windstep_extra_height.zip) to your world folder's datapack folder to increase the step height.

**Comment by milkev** [comment]
works perfectly, thanks!
